# Generated by Django 3.1.1 on 2020-11-29 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttreservation',
            name='resTime',
            field=models.TimeField(default=datetime.time(5, 2, 14, 662954)),
        ),
    ]
