# Generated by Django 3.1.1 on 2020-09-24 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ttMembers',
            new_name='Members',
        ),
        migrations.CreateModel(
            name='ttRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableType', models.IntegerField()),
                ('regDate', models.DateField()),
                ('regTime', models.TimeField()),
                ('memID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrant', to='mySite.members')),
            ],
        ),
    ]
