# Generated by Django 3.1 on 2020-11-29 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblLocation', models.CharField(choices=[('1', 'Floor 1'), ('2', 'Floor 2')], default='1', max_length=2)),
                ('tblType', models.CharField(choices=[('kids', 'Kids Table'), ('adult', 'Adult Table')], default='adult', max_length=5)),
                ('isReserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.CreateModel(
            name='TTReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resDate', models.DateField(default=datetime.date(2020, 11, 29))),
                ('resTime', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='mySite.member')),
                ('tableName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='mySite.tttable')),
            ],
        ),
    ]
