# Generated by Django 3.1.1 on 2020-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_auto_20201129_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttreservation',
            name='resDate',
            field=models.DateField(),
        ),
    ]
