# Generated by Django 3.1 on 2020-11-30 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_auto_20201129_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttreservation',
            name='resDate',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
    ]
