# Generated by Django 3.1.1 on 2020-11-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_auto_20201129_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ttreservation',
            name='resTime',
            field=models.TimeField(),
        ),
    ]
