# Generated by Django 3.1.1 on 2020-11-30 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySite', '0003_auto_20201129_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTcourtLocation', models.CharField(choices=[('out', 'Outdoor'), ('in', 'Indoor')], max_length=3)),
                ('isReserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BTReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTresDate', models.DateField()),
                ('BTresTime', models.TimeField()),
                ('BTCourtName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.btcourt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
