# Generated by Django 3.1.1 on 2020-11-30 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySite', '0004_btcourt_btreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TcourtLocation', models.CharField(choices=[('out', 'Outdoor'), ('in', 'Indoor')], max_length=3)),
                ('isReserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TresDate', models.DateField()),
                ('TresTime', models.TimeField()),
                ('TCourtName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.tcourt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
