# Generated by Django 3.1 on 2020-11-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0005_auto_20201129_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='TTReservation',
        ),
        migrations.DeleteModel(
            name='TTTable',
        ),
    ]
